version: "3.5"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: host
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro'

  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: host
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_HOST_PROMETHEUS=http://localhost:9090
    volumes:
      - './grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards'
      - './grafana/provisioning/datasources:/etc/grafana/provisioning/datasources'
      - './grafana/grafana.ini:/etc/grafana/grafana.ini'
    depends_on:
      - prometheus
