version: "3.5"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    network_mode: host
    expose:
      - 9090
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro'

  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: host
    expose:
      - 3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - './grafana/provisioning/datasources:/etc/grafana/provisioning/datasources'
      - './grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards'
    depends_on:
      - prometheus
