version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "1234!", "--appendonly", "yes"]
#    environment:
#      - REDIS_PASSWORD=minha_senha_forte
    volumes:
      - redis_data:/data
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379:0:1234!
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  redis_data: