global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'docker-host-alpha'

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app'
    scrape_interval: 1s
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['localhost:8080']
#      - targets: ['host.containers.internal:8080','host.docker.internal:8080']